title: SciNLP
# logo: /assets/img/logo.png
# description: The 2nd SciNLP workshop at AKBC 2021.
show_downloads: false
github:
  is_user_page: false
  is_project_page: false
google_analytics:
theme: jekyll-theme-minimal
